### ISSUE TITLE
ConsoleUI: Auto complete of subcommand broken by case insensitive change

### ISSUE THREAD

**Issue by neilstephens** [neilstephens/opendatacon#62]
See comment/review on pull request: https://github.com/neilstephens/opendatacon/pull/60#bottom @cpp-rakesh

**Comment by cpp-rakesh** [comment]
@neilstephens , we can now close this issue, I have tested this at my end and I reckon we have merged the changes as well to develop.

**Comment by neilstephens** [comment]
No, it still doesn't work in the mainline develop branch. I don't think I've merged your final console UI code. Let me know which branch to diff and merge.

**Comment by cpp-rakesh** [comment]
@neilstephens has found a defect related with working on history commands. Tab is crashing the system in PrintMatches. @cpp-rakesh work on this after the WebUI => SimControl implementation along with getting rid of comments from GetCurrentState to WebUI plugin.
